### ISSUE TITLE
Allow an ongoing match to be cancelled

### ISSUE THREAD

**Issue by ilyakava** [ilyakava/pongbot#3]

**Comment by jinpark** [comment]
Can't you do `pongbot decline` ?

**Comment by ilyakava** [comment]
`decline` only rejects a match when it is proposed, but not after it is accepted

**Comment by jinpark** [comment]
Ohhhhhhhhhhhhhhhhhk

**Comment by jinpark** [comment]
`decline` works even after acceptance! Should add this to the readme

**Comment by ilyakava** [comment]
closing b/c as stated above, this feature already exists
